name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v.*
  schedule:
    # Run every week @7:23. 7:23 chosen randomly.
    - cron: '23 7 * * 5'

jobs:
  test:
    name: Test 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          docker build -t test/tiddly:latest .
      - name: Test
        run: |
          env CONTAINER=test/tiddly:latest ./test/bats/bin/bats test/test.bats
      - name: Deploy
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tiddly:latest
