name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*
  schedule:
    # Run every week @7:23. 7:23 chosen randomly.
    - cron: '23 7 * * 5'

jobs:
  test:
    name: Test 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          docker build -t test/tiddly:latest .
      - name: Test
        run: |
          env CONTAINER=test/tiddly:latest ./test/bats/bin/bats test/test.bats
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Compute Version
        id: version
        run: |-
          echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/}"
          # Find the default tiddlywiki version at this commit in the
          # Dockerfile.
          tw_version="$(cat Dockerfile | egrep '^ARG TIDDLYWIKI_VERSION=' | cut -d= -f2)"
          if [[ -z "${tw_version}" ]]; then
            echo "Failed to find TiddlyWiki version" >&2
            exit 1
          fi
          echo "::set-output name=TIDDLYWIKI_VERSION::${tw_version}"
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: jkz0 
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Deploy
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            jkz0/tiddly:latest
            jkz0/tiddly:${{ steps.version.outputs.VERSION }}
            jkz0/tiddly:tiddly-wiki-${{ steps.version.outputs.TIDDLYWIKI_VERSION }}
            ghcr.io/joshkunz/tiddly-docker/tiddly:latest
            ghcr.io/joshkunz/tiddly-docker/tiddly:${{ steps.version.outputs.VERSION }}
            ghcr.io/joshkunz/tiddly-docker/tiddly:tiddly-wiki-${{ steps.version.outputs.TIDDLYWIKI_VERSION }}
